service: serverless-rds-mysql

provider:
  name: aws
  runtime: nodejs10.x
  vpc:
    securityGroupsIds:
      - sg-todo
    subnetIds:
      - subnet-todo
      - subnet-todo1
  region: us-east-2

functions:
  hello:
    handler: handler.hello
  findAll:
    handler: crud/todos.findAll
    events:
      - http:
          path: todos
          method: get
  findOne:
    handler: crud/todos.findOne
    events:
      - http:
          path: todos/{todo}
          method: get
  create:
    handler: crud/todos.create
    events:
      - http:
          path: todos
          method: post
  update:
    handler: crud/todos.update
    events:
      - http:
          path: todos/{todo}
          method: put
